export const SUPPORTED_LANGUAGES = {
    'cmn': 'Mandarin Chinese',
    'spa': 'Spanish',
    'eng': 'English',
    'rus': 'Russian',
    'arb': 'Standard Arabic',
    'ben': 'Bengali',
    'hin': 'Hindi',
    'por': 'Portuguese',
    'ind': 'Indonesian',
    'jpn': 'Japanese',
    'fra': 'French',
    'deu': 'German',
    'jav': 'Javanese',
    'kor': 'Korean',
    'tel': 'Telugu',
    'vie': 'Vietnamese',
    'mar': 'Marathi',
    'ita': 'Italian',
    'tam': 'Tamil',
    'tur': 'Turkish',
    'urd': 'Urdu',
    'guj': 'Gujarati',
    'pol': 'Polish',
    'ukr': 'Ukrainian',
    'kan': 'Kannada',
    'mai': 'Maithili',
    'mal': 'Malayalam',
    'pes': 'Iranian Persian',
    'mya': 'Burmese',
    'swh': 'Swahili (individual language)',
    'sun': 'Sundanese',
    'ron': 'Romanian',
    'pan': 'Panjabi',
    'bho': 'Bhojpuri',
    'amh': 'Amharic',
    'hau': 'Hausa',
    'fuv': 'Nigerian Fulfulde',
    'bos': 'Bosnian',
    'hrv': 'Croatian',
    'nld': 'Dutch',
    'srp': 'Serbian',
    'tha': 'Thai',
    'ckb': 'Central Kurdish',
    'yor': 'Yoruba',
    'uzn': 'Northern Uzbek',
    'zlm': 'Malay (individual language)',
    'ibo': 'Igbo',
    'npi': 'Nepali (individual language)',
    'ceb': 'Cebuano',
    'skr': 'Saraiki',
    'tgl': 'Tagalog',
    'hun': 'Hungarian',
    'azj': 'North Azerbaijani',
    'sin': 'Sinhala',
    'koi': 'Komi-Permyak',
    'ell': 'Modern Greek (1453-)',
    'ces': 'Czech',
    'mag': 'Magahi',
    'run': 'Rundi',
    'bel': 'Belarusian',
    'plt': 'Plateau Malagasy',
    'qug': 'Chimborazo Highland Quichua',
    'mad': 'Madurese',
    'nya': 'Nyanja',
    'zyb': 'Yongbei Zhuang',
    'pbu': 'Northern Pashto',
    'kin': 'Kinyarwanda',
    'zul': 'Zulu',
    'bul': 'Bulgarian',
    'swe': 'Swedish',
    'lin': 'Lingala',
    'som': 'Somali',
    'hms': 'Southern Qiandong Miao',
    'hnj': 'Hmong Njua',
    'ilo': 'Iloko',
    'kaz': 'Kazakh'
};

export const LANGUAGE_CODES = Object.entries(SUPPORTED_LANGUAGES).reduce((acc, [code, name]) => {
    acc[name] = code;
    return acc;
}, {});
